### PR TITLE
Remove DiffBase from REQUIRE

### PR DESCRIPTION
**Pull request by tkf**
DiffBase is not used anymore

### CODE REVIEW

**Comment by pkofod** [comment]
Seems like a pretty good argument :)

**Comment by pkofod** [comment]
> DiffBase is not used anymore

how'd you stumble upon this btw?

**Comment by tkf** [comment]
Thanks for the review and merge.

> > DiffBase is not used anymore
> 
> how'd you stumble upon this btw?

I created scripts to load the whole Manifest.toml and compile them into a system image https://github.com/tkf/julia-sysimage-recipes.  Then I realized that DiffBase was included due to NLsolve while it's source code is not Julia 1.0 compatible because it was giving me an import-time error.

**Comment by pkofod** [comment]
Cool, thanks for making this PR as a result!

**Pull request merged**
