### PR TITLE
Use Walker's suggestions for Anderson acceleration

### PR DESCRIPTION
**Pull request by devmotion**
The current implementation of Anderson acceleration uses a different formulation of the least-squares problem than what was suggested by Walker and Ni in https://users.wpi.edu/~walker/Papers/Walker-Ni,SINUM,V49,1715-1735.pdf and https://users.wpi.edu/~walker/Papers/anderson_accn_algs_imps.pdf, and recomputes the QR decomposition in every step. In this PR I tried to follow those recommendations.

### CODE REVIEW

**Comment by antoine-levitt** [comment]
Thanks, it looks great! @pkofod had a WIP version at https://github.com/pkofod/Anderson.jl, but this one seems more advanced. @pkofod?

**Comment by antoine-levitt** [comment]
(fixes https://github.com/JuliaNLSolvers/NLsolve.jl/issues/128)

**Comment by pkofod** [comment]
> Thanks, it looks great! @pkofod had a WIP version at https://github.com/pkofod/Anderson.jl, but this one seems more advanced. @pkofod?

Yeah, it looks good. I'm ashamed that it has been ignored for so long, but I've been busy elsewhere. I apologize.

Unless you've had any experience using this code since february @devmotion , and want to add something, I think this is pretty much good to go.

**Comment by devmotion** [comment]
No worries, I didn't use or test the code in the last months but only added a similar implementation to OrdinaryDiffEq (that was specifically tailored to the use case there). So I'm fine with it :smiley:

**Pull request merged**
