### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
Added symbol for anderson acceleration.

### CODE REVIEW

**Comment by pkofod** [comment]
Thanks Beasty Blacksmith! Have you tried it out on a problem?

**Comment by BeastyBlacksmith** [comment]
I tried, but it failed ( but it most probably wasn't suited for it ).

**Comment by pkofod** [comment]
Did you play around with the memory length ? The default is 0 so that is effectively Picard iterations

**Comment by BeastyBlacksmith** [comment]
I did, but my function tends to be constant a lot with "dips"

**Comment by pkofod** [comment]
This is not a cross-examination, I'm just curious. What did you end up using?

**Comment by BeastyBlacksmith** [comment]
At the moment I'm using `bboptimize` from BlackBoxOptim.jl, but I'm still completely satisfied. I mean I am doing some parameter estimation for boundary value problems on a set of ODEs.

**Pull request merged**
