### PR TITLE
Fix the eye depreciation

### PR DESCRIPTION
**Pull request by matthieugomez**

### CODE REVIEW

**Comment by pkofod** [comment]
Thanks; ref #187 I just never got around to it, sorry.

Is this a branch you're actually hitting? You may want to have a look at your problem :) (unless there's nothing to do; it's just if the Jacobian is actually singular at the solution, then you'll only get linear convergence, and Newton with line search might be overly expensive. Did you try the trust region one?)

**Comment by pkofod** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/19351

**Comment by matthieugomez** [comment]
It’s just a very puzzling error message to get, so I wanted to remove it.

**Comment by pkofod** [comment]
Should be gone now :) Thanks!

**Pull request merged**
