### PR TITLE
solve #62

### PR DESCRIPTION
**Pull request by matthieugomez**
Could we merge this?
Sorry for new pull request — I messed up the previous one #66 when trying to update it.

### CODE REVIEW

**Comment by KristofferC** [comment]
Isn't this removing the ability to use a `not_in_place` `fg`?

**Comment by matthieugomez** [comment]
Ok, I have pushed a commit without depreciation messages for `not_in_place(f, g)` and `not_in_place(f, g, fg)`.  
I still think it would be better to depreciate them — I doubt people really use `not_in_place(f, g, fg)`.

**Comment by sglyon** [comment]
I'm ok with the merge here. I think enabling Autodiff with `not_in_place` is more beneficial than preserving the `fg` version f `not_in_place`

**Comment by KristofferC** [comment]
Sure, I just noted that the pull request did something extra than what #62 was about. I'm fine with removing the `fg` version of `not_in_place`.

**Comment by matthieugomez** [comment]
Thanks everyone. Just to be clear the final commit does preserve the fg version of not_in_place.

**Pull request merged**
