### PR TITLE
Update NLsolve to NLSolversBase and new LineSearches

### PR DESCRIPTION
**Pull request by pkofod**
If we merge and tag this, I can fix Optim to not depend on ReverseDiff, fix the new ForwardDiff syntax, and tag a new version that is v0.6 only.

### CODE REVIEW

**Comment by KristofferC** [comment]
Hmm, problem is that Pkg downgrades Optim to 0.5 to be able to upgrade ForwardDiff to 0.5 https://travis-ci.org/JuliaNLSolvers/NLsolve.jl/jobs/237406291#L192. So it seems that we need a new Optim tag with support for ForwardDiff 0.5 to be able to merge this?

**Comment by pkofod** [comment]
I don't think so, but I think we may be able to remove Optim as a dependency right?

**Comment by KristofferC** [comment]
Oh yeah, of course.

**Comment by pkofod** [comment]
> Oh yeah, of course.

Which was kind of one of the points of having a SolversBase anyway.

**Comment by KristofferC** [comment]
So plan here is to merge this so that Optim can be updated cleanly. Then update the NLsolve code to the latest linesearch syntax (and deprecate the keyword `linesearch!` for `linesearch`, see https://github.com/JuliaNLSolvers/Optim.jl/issues/285)

**Pull request merged**
